---
- name: "Add Mariadb GPG"
  command: "sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8"

- name: "Add Maridb repository"
  command: sudo add-apt-repository "deb [arch=amd64,arm64,ppc64el] http://mariadb.mirror.liquidtelecom.com/repo/10.4/ubuntu {{ codename }} main"

- name: "Install Mariadb server"
  apt:
    name: ["mariadb-server", "mariadb-common", "python3-pymysql", "mysql-common", "socat", "rsync", "mariadb-client", "libmysqlclient20", "mariadb-backup", "software-properties-common"]
    state: present
    update_cache: yes

- name:  "Copy logrotate conf"
  template: src={{item.src}} dest={{item.dest}} owner=root group=root mode=0644
  with_items:
      - { src: 'mysql-logrotate.conf', dest: '/etc/logrotate.d/mysql-server' }

- name: "Copy mysql conf"
  template: src=my.cnf dest=/etc/my.cnf.d

- name: "Install Mariadb server"
  apt:
    name: ["mariadb-server", "mariadb-common", "python3-pymysql", "mysql-common", "socat", "rsync", "galera-4" "mariadb-client", "galera-arbitrator-4","libmysqlclient20", "mariadb-backup", "software-properties-common", "mariadb-client"]
    state: present


- name: "Start and enable mysql service"
  service: name=mariadb state=started enabled=yes


- name: "Set the root password"
  mysql_user:
    login_user: root
    login_password: ''
    name: root
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    check_implicit_admin: yes
    host: localhost
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name:  "Copy galera node conf"
  template: src={{item.src}} dest={{item.dest}} owner=root group=root mode=0644
  with_items:
      - { src: 'galera.cnf', dest: '/etc/mysql/conf.d/galera.cnf' }

  notify: "Restart mysql server"
